env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - http://193.123.74.115
  parameters:
    failOnError: true
    progressToStdout: false
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: http://193.123.74.115
  type: spider
- parameters:
    maxDuration: 60
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap-baseline.html
    reportTitle: ZAP Scanning Report
    template: traditional-html
  type: report
